### ISSUE TITLE
[DPP-20] Produce list of Ebay urls

### ISSUE THREAD

**Issue by simone-trubian** [simone-trubian/dropp-client#22]
In order to complete DPP-21 it is necessary to have a list of url's to fetch, produce the list following this format:
- BangGood URL;Ebay URL

**Comment by Francesco-Giocondo** [comment]
[urlbgeb-1-up.txt](https://github.com/simone-trubian/dropp-client/files/273067/urlbgeb-1-up.txt)

Gli ultimi otto elementi sono nuovi e non te li avevo ancora passati da inserire nel database.
