### ISSUE TITLE
[DPP-23] Change trigger times for availability checks

### ISSUE THREAD

**Issue by simone-trubian** [simone-trubian/dropp-client#25]
Currently Dropp is triggered four times a day starting from 00:00. Report back by writing a comment to this issue what would be the ideal times to trigger the availability check.

**Comment by Francesco-Giocondo** [comment]
I think the ideal trigger is 1 for day at 11:00am CEST

**Comment by simone-trubian** [comment]
Now the job is running once a day only at 9:00 UTC. The timestamp will be changed so to avoid confusion, please refer to DPP-24
