### ISSUE TITLE
[DPP-36] Analyse variable item responses.

### ISSUE THREAD

**Issue by simone-trubian** [simone-trubian/dropp-client#36]
##### Issue

The variable item response is not handled yet but it also not known what to expect from the server.
##### Task
- Chose a series of variable items pages. (Francesco)
- Find out the structure of the JSON object.
- Find out what is the expected response is for an unavailable item.
###### Blocked by

Issue #64

**Comment by Francesco-Giocondo** [comment]
[multi.txt](https://github.com/simone-trubian/dropp/files/227787/multi.txt)

**Comment by simone-trubian** [comment]
##### Results:

The variable article page is comprised of a **master** item that is pulled using its HTML page and a series of variations that are fetched from the server as JSON objects used to populate the master page. So for each variable item there will be one and one only HTML url and a number of GET URL formatted as JSON.

###### Example multiple item pages

[dispenser](http://eu.banggood.com/Wholesale-Warehouse-Wall-mounted-Soap-Dispenser-Stainless-Steel-Liquid-Soap-Box-wp-Eu-955982.html)
[gator](http://eu.banggood.com/Wholesale-Warehouse-New-7-19mm-Multi-function-Hand-Tools-Universal-Repair-Tools-Five-color-wp-Eu-1041370.html)

###### JSON structure

```
{
  "hideBuy": Number,
  "message": String,
  "stocks": Number,
  "show_stocks": Number,
  "hideSku": Number,
  "final_price": Number,
  "price": Number,
  "format_price": String,
  "currency_tags": String,
  "discount": String
}
```
