### ISSUE TITLE
[DPP-39] Change report email format.

### ISSUE THREAD

**Issue by simone-trubian** [simone-trubian/dropp-client#39]
##### Issue:

The current formatting is based on the actual availability string as it is scraped from the BangGood website, but JSON object will unlikely carry the same strings.
##### Expected outcome:

The new formatting should be able to handle both single and variable items.
##### Proposed format:

Print the name of the item in black and add on the left of the line the availability using the following scheme:
- Available (green)
- Low (orange)
- Out (red)
  @Francesco-Giocondo please comment

**Comment by Francesco-Giocondo** [comment]
Si potrebbe aggiungere un parametro (con un nome generico, tipo "dettaglio") e poi fare tipo:
-     EU Direct | cappello alla moda
   dettaglio: rosso
  In stock, usually dispatched in 1 business day

dove "rosso" è la scritta di una delle possibili variabili del prodotto, ad una misura o un colore a seconda dell'oggetto. Per gli item singoli, senza variazioni, il campo resta vuoto nel report. Che ne dici ?

**Comment by simone-trubian** [comment]
Closed and deprecated by ticket #53
