### ISSUE TITLE
[DPP-57] Create JSON file to upload all iems

### ISSUE THREAD

**Issue by simone-trubian** [simone-trubian/dropp-client#58]
##### Issue:

Version 0.5 introduces changes to the items table, so the best approach is to create a JSON file that contains all the data to be uploaded.
##### JSON object structure:

```
[
      {
        "item_name" : string,
        "source_url" : string,
        "ebay_url": string
      },
      .
      .
      .
]
```
##### Notes:
- Decide where to get the title from.
- Validate JSON structure with [JSONLint](http://jsonlint.com/)

**Comment by Francesco-Giocondo** [comment]
[JSON01.txt](https://github.com/simone-trubian/dropp-client/files/306461/JSON01.txt)
