### ISSUE TITLE
[DPP-63] Update the DB JSON file

### ISSUE THREAD

**Issue by simone-trubian** [simone-trubian/dropp-client#63]
##### Issue

Some of the BangGood URL's in the current version of the JSON file are wrong, which is preventing their availability to be updated.
##### Code changes

Refer to ticket #61 to find out which URL's are wrong, correct the mistakes and re-submit the file.

**Comment by Francesco-Giocondo** [comment]
[JSON01.txt](https://github.com/simone-trubian/dropp-client/files/316690/JSON01.txt)
