### ISSUE TITLE
[DPP-70] Update item JSON

### ISSUE THREAD

**Issue by simone-trubian** [simone-trubian/dropp-client#70]

**Comment by simone-trubian** [comment]
Version 0.6 has been deployed! Please feel free to add to the list any multiple item URL.

**Comment by Francesco-Giocondo** [comment]
[JSON160704.txt](https://github.com/simone-trubian/dropp-client/files/345960/JSON160704.txt)
Questo JSON è totale e sostituisce il precedente. Dal prossimo in poi, se possibile, inserirei solo:
- oggetti nuovi con titolo e relative url
- oggetti già presenti con URL EBAY aggiornate
